#!/usr/bin/env bash

set -e

skip_system_packages="${1}"

os_type="$(uname -s)"

apt_packages="curl git tmux ripgrep zsh"
apt_packages_optional="zip unzip"

###############################################################################
# Detect OS and distro type
###############################################################################

function no_system_packages() {
  cat <<EOF
System package installation isn't supported with your OS / distro.

Please install any dependent packages on your own. You can view the list at:

    https://github.com/sassdavid/dotfiles/blob/main/install

Then re-run the script and explicitly skip installing system packages:

    bash <(curl -sS https://raw.githubusercontent.com/sassdavid/dotfiles/main/install) --skip-system-packages
EOF

  exit 1
}

case "${os_type}" in
Linux*)
  os_type="Linux"

  if [ ! -f "/etc/debian_version" ]; then
    [ -z "${skip_system_packages}" ] && no_system_packages
  fi

  ;;
Darwin*) os_type="macOS" ;;
*)
  os_type="Other"

  [ -z "${skip_system_packages}" ] && no_system_packages

  ;;
esac

###############################################################################
# Install packages using your OS' package manager
###############################################################################

function apt_install_packages {
  sudo add-apt-repository -y ppa:git-core/ppa

  # shellcheck disable=SC2086
  sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ${apt_packages} ${apt_packages_optional}

  sudo apt-get clean && sudo rm -rf /var/lib/apt/lists /var/cache/apt/archives
}

function display_packages {
  if [ "${os_type}" == "Linux" ]; then
    echo "${apt_packages} ${apt_packages_optional}"
  fi
}

if [ -z "${skip_system_packages}" ]; then
  cat <<EOF

If you choose yes, all of the system packages below will be installed:

$(display_packages)

If you choose no, the above packages will not be installed and this script
will exit. This gives you a chance to edit the list of packages if you don't
agree with any of the decisions.

The packages listed after zsh are technically optional but are quite useful.
Keep in mind if you don't install pwgen you won't be able to generate random
passwords using a custom alias that's included in these dotfiles.

EOF
  while true; do
    read -rp "Do you want to install the above packages? (y/n) " yn
    case "${yn}" in
    [Yy]*)
      if [ "${os_type}" == "Linux" ]; then
        apt_install_packages
      fi

      break
      ;;
    [Nn]*) exit 0 ;;
    *) echo "Please answer y or n" ;;
    esac
  done
else
  echo "System package installation was skipped!"
fi

###############################################################################
# Clone dotfiles
###############################################################################

read -rep $'\nWhere do you want to clone these dotfiles to [~/dotfiles]? ' clone_path
clone_path="${clone_path:-"${HOME}/dotfiles"}"

# Ensure path doesn't exist.
while [ -e "${clone_path}" ]; do
  read -rep $'\nPath exists, try again? (y) ' y
  case "${y}" in
  [Yy]*)

    break
    ;;
  *) echo "Please answer y or CTRL+c the script to abort everything" ;;
  esac
done

echo

# This is used to locally develop the install script.
if [ "${DEBUG}" == "1" ]; then
  cp -R "${PWD}/." "${clone_path}"
else
  git clone https://github.com/sassdavid/dotfiles.git "${clone_path}"
fi

###############################################################################
# Create initial directories
###############################################################################

mkdir -p "${HOME}/.config/zsh" "${HOME}/.config/gitalias" \
  "${HOME}/.cache/zsh" "${HOME}/.local/bin" \
  "${HOME}/.local/share" "${HOME}/.local/state" \
  "${HOME}/.aws" "${HOME}/.kube"

###############################################################################
# Personalize git user and setup gitalias
###############################################################################

cp "${clone_path}/.gitconfig.user" "${HOME}/.gitconfig.user"

curl https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt -o "${HOME}/.config/gitalias/gitalias.txt"

###############################################################################
# Install zsh plugins
###############################################################################

"${clone_path}/.local/bin/update-zsh-plugins"

###############################################################################
# Install tpm (tmux plugin manager)
###############################################################################

rm -rf "${HOME}/.tmux/plugins/tpm"
git clone --depth 1 https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"

###############################################################################
# Install fzf (fuzzy finder on the terminal and used by a Vim plugin)
###############################################################################

rm -rf "${HOME}/.local/share/fzf"
git clone --depth 1 https://github.com/junegunn/fzf.git "${HOME}/.local/share/fzf" &&
  yes | "${HOME}/.local/share/fzf/install" --bin --no-update-rc

###############################################################################
# Carefully create symlinks
###############################################################################

cat <<EOF

-------------------------------------------------------------------------------

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv"
ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc"
ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile"
ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases"
ln -fs "${clone_path}/.gitconfig" "${HOME}/.gitconfig"
ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf"
ln -fs "${clone_path}/.local/bin/"* "${HOME}/.local/bin/"

# And if you happen to be using WSL:
sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf

-------------------------------------------------------------------------------

A potentially dangerous action is about to happen. The above files are going to
get forcefully symlinked.

What does that mean?

Any config files you have on the right hand side of the paths are going to get
overwritten with the files that come with my dotfiles (left side).

If you care about your original config files now would be the time to back
them up. They will ALL be overwritten if you say yes to the prompt below.
EOF

while true; do
  read -rep $'\nReady to continue and apply the symlinks? (y) ' y
  case "${y}" in
  [Yy]*)

    break
    ;;
  *) echo "Please answer y or CTRL+c the script to abort everything" ;;
  esac
done

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv" &&
  ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc" &&
  ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile" &&
  ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases" &&
  ln -fs "${clone_path}/.gitconfig" "${HOME}/.gitconfig" &&
  ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf" &&
  ln -fs "${clone_path}/.local/bin/"* "${HOME}/.local/bin/"

if grep -qE "(Microsoft|microsoft|WSL)" /proc/version &>/dev/null; then
  sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf
fi

###############################################################################
# Change default shell to zsh
###############################################################################

[ "${os_type}" != "macOS" ] && chsh -s "$(command -v zsh)"

# shellcheck disable=SC1090
. "${HOME}/.config/zsh/.zprofile"

###############################################################################
# Install mise
###############################################################################

printf "\n\nInstalling latest mise...\n"

curl https://mise.jdx.dev/install.sh | sh

eval "$("${HOME}"/.local/bin/mise activate bash)"

export MISE_FETCH_REMOTE_VERSIONS_TIMEOUT="30s"
export MISE_GO_SET_GOPATH="false"
export MISE_GO_SKIP_CHECKSUM="true"
export MISE_LEGACY_VERSION_FILE="false"
export MISE_NOT_FOUND_AUTO_INSTALL="false"
export MISE_PARANOID="false"
export MISE_DISABLE_DEFAULT_SHORTHANDS="true"

###############################################################################
# Install tmux plugins
###############################################################################

printf "\n\nInstalling tmux plugins...\n"

export TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins"
"${HOME}/.tmux/plugins/tpm/bin/install_plugins"

###############################################################################
# Install latest jq and yq binaries
###############################################################################

printf "\n\nInstalling latest jq and yq binaries...\n"

mise plugins install jq https://github.com/lsanwick/asdf-jq.git
mise plugins install yq https://github.com/sudermanjr/asdf-yq.git

mise install jq@latest
mise install yq@latest

mise use -g --pin jq@latest
mise use -g --pin yq@latest

###############################################################################
# Install latest aws binary
###############################################################################

printf "\n\nInstalling latest aws binary...\n"

mise plugins install awscli https://github.com/MetricMike/asdf-awscli.git

mise install awscli@latest

mise use -g --pin awscli@latest

###############################################################################
# Install latest terraform binary
###############################################################################

printf "\n\nInstalling latest terraform, terragrunt, tflint and terraform-docs binaries...\n"

mise plugins install terraform https://github.com/asdf-community/asdf-hashicorp.git
mise plugins install terragrunt https://github.com/ohmer/asdf-terragrunt
mise plugins install terraform-docs https://github.com/looztra/asdf-terraform-docs
mise plugins install tflint https://github.com/skyzyx/asdf-tflint

mise install terraform@latest
mise install terragrunt@latest
mise install terraform-docs@latest
mise install tflint@latest

mise use -g --pin terraform@latest
mise use -g --pin terragrunt@latest
mise use -g --pin terraform-docs@latest
mise use -g --pin tflint@latest

###############################################################################
# Install kubectl binary
###############################################################################

printf "\n\nInstalling kubectl binary...\n"

mise plugins install kubectl https://github.com/asdf-community/asdf-kubectl.git

mise install kubectl@1.25.16

mise use -g --pin kubectl@1.25.16

###############################################################################
# Install k9s binary
###############################################################################

printf "\n\nInstalling k9s binary...\n"

mise plugins install k9s https://github.com/looztra/asdf-k9s

mise install k9s@0.26.7

mise use -g --pin k9s@0.26.7

###############################################################################
# Install latest helm binary
###############################################################################

printf "\n\nInstalling helm binary...\n"

mise plugins install helm https://github.com/Antiarchitect/asdf-helm.git

mise install helm@latest

mise use -g --pin helm@latest

###############################################################################
# Install latest argocd binary
###############################################################################

printf "\n\nInstalling latest argocd binary...\n"

mise plugins install argocd https://github.com/beardix/asdf-argocd.git

mise install argocd@latest

mise use -g --pin argocd@latest

###############################################################################
# Install latest docker-credential-ecr-login binary
###############################################################################

printf "\n\nInstalling latest docker-credential-ecr-login binary...\n"

mise plugins install amazon-ecr-credential-helper https://github.com/dex4er/asdf-amazon-ecr-credential-helper.git

mise install amazon-ecr-credential-helper@latest

mise use -g --pin amazon-ecr-credential-helper@latest

###############################################################################
# Install latest go binary
###############################################################################

printf "\n\nInstalling latest go binary...\n"

mise install go@latest

mise use -g --pin go@latest

###############################################################################
# Install latest java and maven binaries
###############################################################################

printf "\n\nInstalling latest java and maven binaries...\n"

mise plugins install maven https://github.com/halcyon/asdf-maven.git

mise install java@corretto-17
mise install maven@latest

mise use -g --pin java@corretto-17
mise use -g --pin maven@latest

###############################################################################
# Install kafka binaries
###############################################################################

printf "\n\nInstalling kafka...\n"

mise plugins install kafka https://github.com/ueisele/asdf-kafka.git

mise install kafka@apache-3.3.2

mise use -g --pin kafka@apache-3.3.2

###############################################################################
# Install pre-commit
###############################################################################

printf "\n\nInstalling pre-commit...\n"

mise plugins install pre-commit https://github.com/jonathanmorley/asdf-pre-commit.git

mise install pre-commit@latest

mise use -g --pin pre-commit@latest

###############################################################################
# Done!
###############################################################################

cat <<EOF
Everything was installed successfully!

You can safely close this terminal.

The next time you open your terminal zsh will be ready to go!
EOF

exit 0
