#!/usr/bin/env bash

set -e

skip_system_packages="${1}"

os_type="$(uname -s)"

apt_packages="curl git tmux ripgrep zsh"
apt_packages_optional="jq zip unzip python3.10 python3.10-venv python3.11 python3.11-venv python3.12 python3.12-venv"

install_asdf_version="v0.13.1"

###############################################################################
# Detect OS and distro type
###############################################################################

function no_system_packages() {
  cat <<EOF
System package installation isn't supported with your OS / distro.

Please install any dependent packages on your own. You can view the list at:

    https://github.com/sassdavid/dotfiles/blob/main/install

Then re-run the script and explicitly skip installing system packages:

    bash <(curl -sS https://raw.githubusercontent.com/sassdavid/dotfiles/main/install) --skip-system-packages
EOF

  exit 1
}

case "${os_type}" in
Linux*)
  os_type="Linux"

  if [ ! -f "/etc/debian_version" ]; then
    [ -z "${skip_system_packages}" ] && no_system_packages
  fi

  ;;
Darwin*) os_type="macOS" ;;
*)
  os_type="Other"

  [ -z "${skip_system_packages}" ] && no_system_packages

  ;;
esac

###############################################################################
# Install packages using your OS' package manager
###############################################################################

function apt_install_packages {
  sudo add-apt-repository -y ppa:git-core/ppa
  sudo add-apt-repository -y ppa:deadsnakes/ppa

  # shellcheck disable=SC2086
  sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get install -y ${apt_packages} ${apt_packages_optional}

  sudo apt-get clean && sudo rm -rf /var/lib/apt/lists /var/cache/apt/archives
}

function display_packages {
  if [ "${os_type}" == "Linux" ]; then
    echo "${apt_packages} ${apt_packages_optional}"
  fi
}

if [ -z "${skip_system_packages}" ]; then
  cat <<EOF

If you choose yes, all of the system packages below will be installed:

$(display_packages)

If you choose no, the above packages will not be installed and this script
will exit. This gives you a chance to edit the list of packages if you don't
agree with any of the decisions.

The packages listed after zsh are technically optional but are quite useful.
Keep in mind if you don't install pwgen you won't be able to generate random
passwords using a custom alias that's included in these dotfiles.

EOF
  while true; do
    read -rp "Do you want to install the above packages? (y/n) " yn
    case "${yn}" in
    [Yy]*)
      if [ "${os_type}" == "Linux" ]; then
        apt_install_packages
      fi

      break
      ;;
    [Nn]*) exit 0 ;;
    *) echo "Please answer y or n" ;;
    esac
  done
else
  echo "System package installation was skipped!"
fi

###############################################################################
# Clone dotfiles
###############################################################################

read -rep $'\nWhere do you want to clone these dotfiles to [~/dotfiles]? ' clone_path
clone_path="${clone_path:-"${HOME}/dotfiles"}"

# Ensure path doesn't exist.
while [ -e "${clone_path}" ]; do
  read -rep $'\nPath exists, try again? (y) ' y
  case "${y}" in
  [Yy]*)

    break
    ;;
  *) echo "Please answer y or CTRL+c the script to abort everything" ;;
  esac
done

echo

# This is used to locally develop the install script.
if [ "${DEBUG}" == "1" ]; then
  cp -R "${PWD}/." "${clone_path}"
else
  git clone https://github.com/sassdavid/dotfiles.git "${clone_path}"
fi

###############################################################################
# Create initial directories
###############################################################################

mkdir -p "${HOME}/.config/zsh" "${HOME}/.config/gitalias" \
  "${HOME}/.cache/zsh" "${HOME}/.local/bin" \
  "${HOME}/.local/share" "${HOME}/.local/state" \
  "${HOME}/.aws" "${HOME}/.kube"

###############################################################################
# Personalize git user and setup gitalias
###############################################################################

cp "${clone_path}/.gitconfig.user" "${HOME}/.gitconfig.user"

curl https://raw.githubusercontent.com/GitAlias/gitalias/main/gitalias.txt -o "${HOME}/.config/gitalias/gitalias.txt"

###############################################################################
# Install zsh plugins
###############################################################################

"${clone_path}/.local/bin/update-zsh-plugins"

###############################################################################
# Install tpm (tmux plugin manager)
###############################################################################

rm -rf "${HOME}/.tmux/plugins/tpm"
git clone --depth 1 https://github.com/tmux-plugins/tpm "${HOME}/.tmux/plugins/tpm"

###############################################################################
# Install fzf (fuzzy finder on the terminal and used by a Vim plugin)
###############################################################################

rm -rf "${HOME}/.local/share/fzf"
git clone --depth 1 https://github.com/junegunn/fzf.git "${HOME}/.local/share/fzf" &&
  yes | "${HOME}/.local/share/fzf/install" --bin --no-update-rc

###############################################################################
# Carefully create symlinks
###############################################################################

cat <<EOF

-------------------------------------------------------------------------------

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv"
ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc"
ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile"
ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases"
ln -fs "${clone_path}/.config/zsh/.asdfrc" "${HOME}/.config/zsh/.asdfrc"
ln -fs "${clone_path}/.gitconfig" "${HOME}/.gitconfig"
ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf"
ln -fs "${clone_path}/.local/bin/"* "${HOME}/.local/bin/"

# And if you happen to be using WSL:
sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf

-------------------------------------------------------------------------------

A potentially dangerous action is about to happen. The above files are going to
get forcefully symlinked.

What does that mean?

Any config files you have on the right hand side of the paths are going to get
overwritten with the files that come with my dotfiles (left side).

If you care about your original config files now would be the time to back
them up. They will ALL be overwritten if you say yes to the prompt below.
EOF

while true; do
  read -rep $'\nReady to continue and apply the symlinks? (y) ' y
  case "${y}" in
  [Yy]*)

    break
    ;;
  *) echo "Please answer y or CTRL+c the script to abort everything" ;;
  esac
done

ln -fs "${clone_path}/.zshenv" "${HOME}/.zshenv" &&
  ln -fs "${clone_path}/.config/zsh/.zshrc" "${HOME}/.config/zsh/.zshrc" &&
  ln -fs "${clone_path}/.config/zsh/.zprofile" "${HOME}/.config/zsh/.zprofile" &&
  ln -fs "${clone_path}/.config/zsh/.aliases" "${HOME}/.config/zsh/.aliases" &&
  ln -fs "${clone_path}/.config/zsh/.asdfrc" "${HOME}/.config/zsh/.asdfrc" &&
  ln -fs "${clone_path}/.gitconfig" "${HOME}/.gitconfig" &&
  ln -fs "${clone_path}/.tmux.conf" "${HOME}/.tmux.conf" &&
  ln -fs "${clone_path}/.local/bin/"* "${HOME}/.local/bin/"

if grep -qE "(Microsoft|microsoft|WSL)" /proc/version &>/dev/null; then
  sudo ln -fs "${clone_path}/etc/wsl.conf" /etc/wsl.conf
fi

###############################################################################
# Change default shell to zsh
###############################################################################

[ "${os_type}" != "macOS" ] && chsh -s "$(command -v zsh)"

# shellcheck disable=SC1090
. "${HOME}/.config/zsh/.zprofile"

###############################################################################
# Install asdf and Node (Node is used for 1 Vim plugin)
###############################################################################

printf "\n\nInstalling asdf %s...\n" "${install_asdf_version}"

export ASDF_CONFIG_FILE="${HOME}/.config/.asdfrc"
export ASDF_DIR="${HOME}/.config/asdf"
export ASDF_DATA_DIR="${HOME}/.asdf"

rm -rf "${ASDF_DIR}"
git clone --depth 1 https://github.com/asdf-vm/asdf.git --branch "${install_asdf_version}" \
  "${ASDF_DIR}"

# shellcheck disable=SC1090
. "${ASDF_DIR}/asdf.sh"

###############################################################################
# Install tmux plugins
###############################################################################

printf "\n\nInstalling tmux plugins...\n"

export TMUX_PLUGIN_MANAGER_PATH="${HOME}/.tmux/plugins"
"${HOME}/.tmux/plugins/tpm/bin/install_plugins"

###############################################################################
# Install latest aws binary
###############################################################################

printf "\n\nInstalling latest aws binary...\n"

asdf plugin add awscli https://github.com/MetricMike/asdf-awscli.git

asdf install awscli latest

asdf global awscli latest

###############################################################################
# Install latest terraform binary
###############################################################################

printf "\n\nInstalling latest terraform, terragrunt, tflint and terraform-docs binaries...\n"

asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
asdf plugin add terragrunt https://github.com/ohmer/asdf-terragrunt
asdf plugin add terraform-docs https://github.com/looztra/asdf-terraform-docs
asdf plugin add tflint https://github.com/skyzyx/asdf-tflint

asdf install terraform latest
asdf install terragrunt latest
asdf install terraform-docs latest
asdf install tflint latest

asdf global terraform latest
asdf global terragrunt latest
asdf global terraform-docs latest
asdf global tflint latest

###############################################################################
# Install kubectl binary
###############################################################################

printf "\n\nInstalling kubectl binary...\n"

asdf plugin-add kubectl https://github.com/asdf-community/asdf-kubectl.git

asdf install kubectl 1.25.16

asdf global kubectl 1.25.16

###############################################################################
# Install latest helm binary
###############################################################################

printf "\n\nInstalling helm binary...\n"

asdf plugin-add helm https://github.com/Antiarchitect/asdf-helm.git

asdf install helm latest

asdf global helm latest

###############################################################################
# Install latest argocd binary
###############################################################################

printf "\n\nInstalling latest argocd binary...\n"

asdf plugin-add argocd https://github.com/beardix/asdf-argocd.git

asdf install argocd latest

asdf global argocd latest

###############################################################################
# Install latest docker-credential-ecr-login binary
###############################################################################

printf "\n\nInstalling latest docker-credential-ecr-login binary...\n"

"${clone_path}/.local/bin/get-amazon-ecr-credential-helper"

###############################################################################
# Install latest go binary
###############################################################################

printf "\n\nInstalling latest go binary...\n"

"${clone_path}/.local/bin/get-go"

###############################################################################
# Install pip and pre-commit
###############################################################################

printf "\n\nInstalling pip and pre-commit...\n"

"${clone_path}/.local/bin/get-precommit"

###############################################################################
# Install k9s binary
###############################################################################

printf "\n\nInstalling k9s binary...\n"

"${clone_path}/.local/bin/get-k9s"

###############################################################################
# Done!
###############################################################################

cat <<EOF
Everything was installed successfully!

You can safely close this terminal.

The next time you open your terminal zsh will be ready to go!
EOF

exit 0
